//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTransacciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor_Transacciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor_Transacciones()
        {
            this.Aplica_Transacciones = new HashSet<Aplica_Transacciones>();
        }
    
        public string Cedula { get; set; }
        public string Email { get; set; }
        public string NombreP { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplica_Transacciones> Aplica_Transacciones { get; set; }
    }
}
